In [1]:
#Task 1. Write a program that allows you enter 4 numbers and store them in a file called 'Number-file#
da_number = input("Enter your first Number")
number_file = open("number_file.txt", "w")
number_file.write(da_number)
da_number1 = input("Enter your second Number")
number_file = open("number_file.txt", "a")
number_file.write(da_number1)
da_number2 = input("Enter your third Number")
number_file = open("number_file.txt", "a")
number_file.write(da_number2)
da_number3 = input("Enter your fourth Number")
number_file = open("number_file.txt", "a")
number_file.write(da_number3)
number_file.close()


In [23]:
#Task 2
def mark_grade():
    if per_mark > 70:
        print("Congrats, your grade is first class")
    elif per_mark == <70 and !>50:
        print("You have been awarded second class")
    elif per_mark < 50:
        print("You have been awarded third class")
    else:
        print("You have entered a wrong score, try again")

per_mark = int(input("Please input your percentage mark"))
mark_grade()

SyntaxError: invalid syntax (<ipython-input-23-3f339da92510>, line 5)

In [25]:
#Task 3.1 - Crest a 1D array of numbers from 0-9

array = np.array([0,1,2,3,4,5,6,7,8,9])

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
#Task 3.2 - Create a 3*3 Numpy array of all boolean values Trues.
#In python, true=1, false=0

np.ones([3,3], dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
#Task 3.3 - Extract all odd numbers from array of 1-10
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [31]:
#Task 3.4 - Replace all odd numbers in an array of 1-10 with the value -1
b = np.array([1,2,3,4,5,6,7,8,9,10])
b[b % 2 == 1] = -1
print(b)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [34]:
#Task 3.5 - Convert a 1D array to a 2D array with 2 rows
x = np.array([1,2,3,4])
y = np.reshape(x, (-1,2))
y

array([[1, 2],
       [3, 4]])

In [39]:
#Task  - Create two arrays a and b, stack these two arrays vertically and use the np.dot and np.sum to calculate totals
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)
d = np.sum(c)
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944
